# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-25 14:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hello',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='myapp_hello', serialize=False, to='cms.CMSPlugin')),
                ('guest_name', models.CharField(default='Guest', max_length=50)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='SubjectCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='国标编码')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('show', models.BooleanField(default=True, verbose_name='是否展示')),
            ],
            options={
                'verbose_name': '稿件学科分类',
                'verbose_name_plural': '稿件学科分类',
                'managed': True,
            },
        ),
        migrations.AlterIndexTogether(
            name='subjectcategory',
            index_together=set([('show', 'order')]),
        ),
    ]
